github workflows: added tests

diff --git a/.github/workflows/linux-build-9.yml b/.github/workflows/linux-build-9.yml
--- a/.github/workflows/linux-build-9.yml
+++ b/.github/workflows/linux-build-9.yml
@@ -84,13 +84,13 @@ jobs:
             echo "::error::Failure during Build"
             exit 1
           }
-#      - name: Run Tests
-#        working-directory: build
-#        run: |
-#          LD_LIBRARY_PATH="$HOME/tcl_install/lib" make test || {
-#            echo "::error::Failure during Test"
-#            exit 1
-#          }
+      - name: Run Tests
+        working-directory: build
+        run: |
+          LD_LIBRARY_PATH="$HOME/tcl_install/lib" make test || {
+            echo "::error::Failure during Test"
+            exit 1
+          }
       - name: Test-Drive Installation
         working-directory: build
         run: |
