github workflows: install openssl to home dir

diff --git a/.github/workflows/linux-build-9.yml b/.github/workflows/linux-build-9.yml
--- a/.github/workflows/linux-build-9.yml
+++ b/.github/workflows/linux-build-9.yml
@@ -49,7 +49,10 @@ jobs:
       - name: Configure openssl
         working-directory: openssl
         run: |
-          ./Configure no-docs
+          ./Configure no-docs --prefix=$HOME/twebserver_install || {
+            echo "::error::Failure during Configure openssl"
+            exit 1
+          }
       - name: Build openssl
         working-directory: openssl
         run: |
